1. 导入numpy库并简写为 np (★☆☆)

In [3]:
import numpy as np

2. 打印numpy的版本和配置说明 (★☆☆)

In [6]:
np.__version__
# np.show_config()

'1.16.2'

3. 创建一个长度为10的空向量 (★☆☆)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. 如何找到任何一个数组的内存大小？ (★☆☆)

In [20]:
a = np.random.randn(5,6,9,8,89,8)
a.size* a.itemsize

12303360

5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [22]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [23]:
a = np.zeros(10)
a[4] =1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. 创建一个值域范围从10到49的向量(★☆☆)

In [24]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. 反转一个向量(第一个元素变为最后一个) (★☆☆)*******************

In [27]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [28]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

11. 创建一个 3x3 的单位矩阵 (★☆☆)

In [29]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

12. 创建一个 3x3x3的随机数组 (★☆☆)

In [31]:
np.random.randn(3,3)

array([[ 0.37056737,  0.29369813, -0.68771695],
       [ 0.60214773,  0.69334805,  0.23585273],
       [-0.4087868 ,  0.0564501 , -1.66926676]])

13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)

In [33]:
a = np.random.randn(10,10)
np.max(a)
np.min(a)

-3.3216534038959606

14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)

In [34]:
np.mean(np.random.randn(1,10))

0.01039809805379025

15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)

In [39]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

In [41]:
a = np.ones((10,10))
Z = np.pad(a, pad_width =1, mode = 'constant', constant_values =0)
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

17. 以下表达式运行的结果分别是什么? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [46]:
0.3 == 3 * 0.1


False

nan
False
False
nan
True

18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)
# Z = np.diag(1+np.arange(4),k=-1)
# print(Z)

In [47]:
Z = np.diag(1+np.arange(4), k= -1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)

In [48]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [49]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [50]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化(★☆☆)

In [51]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.81601653 0.92313907 0.49626362 0.35861095 0.60463349]
 [0.         0.98882214 0.1976554  0.1306142  0.53440055]
 [0.75897123 0.14943853 0.51557874 0.99177414 0.40428798]
 [0.49590213 0.0594442  0.92745744 0.10650562 0.0806274 ]
 [0.40776746 0.21943157 0.42971268 0.50687692 1.        ]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)

In [52]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)

In [53]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)

In [54]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么? (★☆☆)
(提示: np.sum)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [55]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [56]:
Z = np.arange(5)
Z ** Z  # legal

array([  1,   1,   4,  27, 256], dtype=int32)

28. 下列表达式的结果分别是什么?(★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [59]:
print(np.array(0) / np.array(0))
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

nan


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

29. 如何从零位对浮点数组做舍入 ? (★☆☆)

In [60]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -3.  -8.   3.   5.   2. -10.  -8.   6.   1.  -4.]


30. 如何找到两个数组中的共同元素? (★☆☆)

In [61]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 4 9]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)

In [63]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. 下面的表达式是正确的吗? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [64]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. 如何得到昨天，今天，明天的日期? (★☆☆)

In [65]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-23
Today is 2019-06-24
Tomorrow is 2019-06-25


34. 如何得到所有与2016年7月对应的日期？ (★★☆)

In [66]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)

In [68]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆)

In [73]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))



[0. 1. 0. 3. 9. 1. 0. 0. 3. 0.]
[0. 1. 0. 3. 9. 1. 0. 0. 3. 0.]
[0. 1. 0. 3. 9. 1. 0. 0. 3. 0.]
[0 1 0 3 9 1 0 0 3 0]
[0. 1. 0. 3. 9. 1. 0. 0. 3. 0.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)

In [74]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)

In [75]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)

In [76]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序 (★★☆)

In [79]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.0325706  0.03767029 0.06124701 0.06964622 0.09600804 0.1992363
 0.23510715 0.24279319 0.46159906 0.73915326]


41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)

In [80]:
Z = np.arange(10)
np.add.reduce(Z)

45

42. 对于两个随机数组A和B，检查它们是否相等(★★☆)

In [82]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


43. 创建一个只读数组(read-only) (★★☆)

In [83]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)

In [84]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.37736913 0.82266819 0.87617144 0.75863589 1.09390709 1.01156777
 0.58910484 0.99735881 0.97438622 0.89212603]
[0.05885644 0.68588434 0.15941513 1.38482738 1.07369194 0.46155185
 0.30402672 1.53665732 0.87830699 1.08696962]


45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)

In [85]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.01377145 0.58058597 0.47557713 0.         0.60456018 0.4101108
 0.6871942  0.20043001 0.6210157  0.38824231]


46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)

In [86]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [87]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


48. 打印每个numpy标量类型的最小值和最大值？ (★★☆)

In [88]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何打印一个数组中的所有数值? (★★☆)

In [91]:
np.set_printoptions(threshold=10000)
Z = np.zeros((16,16))
print (Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. 给定标量时，如何找到数组中最接近标量的值？(★★☆)

In [92]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

59


51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组(★★☆)

In [93]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离(★★☆)

In [94]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.3286719  0.58592854 0.24110961 0.69300297 0.05905348
  0.37511649 0.84173047 0.77671065 0.61968174]
 [0.3286719  0.         0.25756943 0.15345027 0.78214678 0.37221472
  0.05543274 0.53913201 0.55903347 0.36979821]
 [0.58592854 0.25756943 0.         0.37914557 0.91757717 0.62732164
  0.21760417 0.32536888 0.46854328 0.28973852]
 [0.24110961 0.15345027 0.37914557 0.         0.63896609 0.26560755
  0.20852123 0.60369878 0.54418651 0.37927392]
 [0.69300297 0.78214678 0.91757717 0.63896609 0.         0.64972196
  0.83208407 0.93999259 0.67492447 0.69518191]
 [0.05905348 0.37221472 0.62732164 0.26560755 0.64972196 0.
  0.42151383 0.86925496 0.78456904 0.63737642]
 [0.37511649 0.05543274 0.21760417 0.20852123 0.83208407 0.42151383
  0.         0.51785788 0.5673386  0.37459315]
 [0.84173047 0.53913201 0.32536888 0.60369878 0.93999259 0.86925496
  0.51785788 0.         0.29533176 0.26279459]
 [0.77671065 0.55903347 0.46854328 0.54418651 0.67492447 0.78456904
  0.5673386  0.29533

53. 如何将32位的浮点数(float)转换为对应的整数(integer)?

In [95]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


54. 如何读取以下文件? (★★☆)

1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [98]:
np.genfromtxt

<function numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')>

55. 对于numpy数组，enumerate的等价操作是什么？(★★☆)

In [99]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. 生成一个通用的二维Gaussian-like数组 (★★☆)

In [100]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. 对一个二维数组，如何在其内部随机放置p个元素? (★★☆)

In [101]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


58. 减去一个矩阵中的每一行的平均值 (★★☆)

In [102]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.36551515 -0.40977862  0.46361912 -0.34687718  0.04284092  0.11881446
   0.30752305  0.31055123  0.10796372 -0.22914155]
 [-0.04707705 -0.35685214  0.28499951  0.16682162 -0.06390885 -0.25899023
  -0.3879579   0.25223057  0.42923022 -0.01849573]
 [ 0.18965351 -0.21369212 -0.46435307 -0.05985709  0.07469498  0.15873681
  -0.36466825  0.24751561  0.23515924  0.19681038]
 [ 0.46116941 -0.31192249  0.39964839  0.31280352 -0.36275319 -0.24094138
  -0.3508369   0.12699621 -0.23386706  0.19970349]
 [ 0.36151957  0.09637686 -0.40062803  0.16149971 -0.35851891  0.42704678
  -0.23194318 -0.15150657  0.37378214 -0.27762838]]


59. 如何通过第n列对一个数组进行排序? (★★☆)

In [103]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[1 0 0]
 [1 5 9]
 [8 4 8]]
[[1 0 0]
 [8 4 8]
 [1 5 9]]


60. 如何检查一个二维数组是否有空列？(★★☆)

In [104]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


61. 从数组中的给定值中找出最近的值 (★★☆)

In [105]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.47899580518670193


62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组? (★★☆)

In [106]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. 创建一个具有name属性的数组类(★★☆)

In [107]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? (★★★)

In [108]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 3. 3. 3. 2. 3. 3. 4. 4.]


65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)? (★★★)

In [109]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量(★★★)

In [110]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？ (★★★)

In [111]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[53 56 49 41]
 [41 64 62 52]
 [66 46 55 51]]


68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？(★★★)

In [112]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.58353239 0.60090595 0.34250271 0.50965612 0.52561791 0.50463715
 0.60589697 0.59554991 0.47909335 0.61342541]


69. 如何获得点积 dot prodcut的对角线? (★★★)

In [113]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([1.42234646, 1.39666962, 0.79436558, 1.9164772 , 0.72969639])

70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？(★★★)

In [114]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？(★★★)

In [115]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. 如何对一个数组中任意两行做交换? (★★★)

In [116]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [117]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 34) ( 0, 60) ( 3,  9) ( 3, 38) ( 7, 31) ( 7, 91) ( 9, 38) (16, 21)
 (16, 48) (21, 48) (26, 75) (26, 89) (27, 66) (27, 87) (31, 91) (34, 60)
 (36, 63) (36, 91) (37, 61) (52, 67) (52, 93) (61, 61) (63, 91) (66, 87)
 (67, 93) (75, 89) (78, 82) (78, 95) (82, 95)]


74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C(★★★)

In [118]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


75. 如何通过滑动窗口计算一个数组的平均数? (★★★)

In [119]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [120]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？(★★★)

In [121]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1])

78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？(★★★)

In [122]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 3.81947073  8.81716558  5.52913688  2.50816522  8.71936837  7.19399671
 10.5133842   1.55518922  3.42146519  4.85163836]


79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？(★★★)

In [123]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.40585867 16.88185434  2.50183942 15.42847382  4.54344162  5.14733083
   2.53637682 11.22734981  3.25625596  8.75895262]
 [ 6.91125989  6.21643739  2.95435243  6.35352429 13.67726684  9.082598
   7.00918087  4.29083363  7.24880035  1.36892392]
 [ 2.14743676 12.0606437   4.52430001 12.02954572  9.93785657  8.73338724
   6.34491763  9.2605661   1.36925616  3.20904083]
 [ 5.33908961  4.32756798  3.91266672  2.05855989 10.45857629  2.87347697
   0.97361737  1.40426434  9.58011442  0.55074357]
 [ 8.62627611  3.92909554  2.03441178  4.0138194  14.92815525  8.91559652
   6.96893223  2.14933961  9.57067724  2.99739112]
 [ 5.42123027 10.68550302  8.55464082 12.39618745 13.88065366 13.18927984
  10.8253163  10.91997517  2.45451813  0.21987013]
 [ 0.53330113 15.19833066  7.29540175 15.82293869  9.27254996 10.46270904
   7.88334264 13.16848972  1.91808839  4.63624415]
 [ 4.36037326 11.07564861 10.68099096  5.29252924  0.16704546  6.06006608
   8.2269168   1.18304859  3.37281472 10.42343124]
 [

80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [124]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[2 1 7 0 6 9 5 1 8 3]
 [1 5 4 1 3 8 3 8 8 7]
 [9 0 2 0 9 9 7 8 0 9]
 [6 9 6 3 6 7 9 9 4 7]
 [7 6 9 1 4 8 1 3 7 9]
 [6 8 1 2 4 2 6 3 1 8]
 [3 9 0 2 4 2 3 0 6 0]
 [9 3 7 6 1 2 5 8 3 9]
 [3 8 6 7 5 8 9 1 0 9]
 [2 9 7 1 1 9 1 8 3 4]]
[[0 0 0 0 0]
 [0 2 1 7 0]
 [0 1 5 4 1]
 [0 9 0 2 0]
 [0 6 9 6 3]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? (★★★)

In [125]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算一个矩阵的秩(★★★)

In [126]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


83. 如何找到一个数组中出现频率最高的值？

In [127]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

9


84. 从一个10x10的矩阵中提取出连续的3x3区块(★★★)

In [128]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[1 4 1]
   [0 1 2]
   [4 1 2]]

  [[4 1 0]
   [1 2 3]
   [1 2 2]]

  [[1 0 3]
   [2 3 1]
   [2 2 3]]

  [[0 3 0]
   [3 1 2]
   [2 3 1]]

  [[3 0 2]
   [1 2 0]
   [3 1 0]]

  [[0 2 0]
   [2 0 1]
   [1 0 4]]

  [[2 0 0]
   [0 1 2]
   [0 4 3]]

  [[0 0 0]
   [1 2 4]
   [4 3 4]]]


 [[[0 1 2]
   [4 1 2]
   [0 3 4]]

  [[1 2 3]
   [1 2 2]
   [3 4 1]]

  [[2 3 1]
   [2 2 3]
   [4 1 0]]

  [[3 1 2]
   [2 3 1]
   [1 0 3]]

  [[1 2 0]
   [3 1 0]
   [0 3 1]]

  [[2 0 1]
   [1 0 4]
   [3 1 1]]

  [[0 1 2]
   [0 4 3]
   [1 1 4]]

  [[1 2 4]
   [4 3 4]
   [1 4 1]]]


 [[[4 1 2]
   [0 3 4]
   [1 4 3]]

  [[1 2 2]
   [3 4 1]
   [4 3 4]]

  [[2 2 3]
   [4 1 0]
   [3 4 2]]

  [[2 3 1]
   [1 0 3]
   [4 2 2]]

  [[3 1 0]
   [0 3 1]
   [2 2 1]]

  [[1 0 4]
   [3 1 1]
   [2 1 2]]

  [[0 4 3]
   [1 1 4]
   [1 2 4]]

  [[4 3 4]
   [1 4 1]
   [2 4 2]]]


 [[[0 3 4]
   [1 4 3]
   [4 4 3]]

  [[3 4 1]
   [4 3 4]
   [4 3 4]]

  [[4 1 0]
   [3 4 2]
   [3 4 2]]

  [[1 0 3]
   [4 2 2]
   [4 2 1]]

  [[0 3 1]
   

85. 创建一个满足 Z[i,j] == Z[j,i]的子类 (★★★)

In [129]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 1  7 12  0  8]
 [ 7  0  5  3  6]
 [12  5  9 42  7]
 [ 0  3 42  6  0]
 [ 8  6  7  0  6]]


86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？(★★★)

In [133]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
# It works, because:
M is (p,n,n)
V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


False

87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? (★★★)

In [134]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. 如何利用numpy数组实现Game of Life? (★★★)

In [135]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

89. 如何找到一个数组的第n个最大值? (★★★)

In [136]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)(★★★)

In [137]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. 如何从一个正常数组创建记录数组(record array)? (★★★)

In [138]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. 考虑一个大向量Z, 用三种不同的方法计算它的立方(★★★)

In [139]:
x = np.random.rand()
np.power(x,3)

0.6610612687547767

93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？ (★★★)

In [140]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[2 3 4 7]


94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) (★★★)

In [141]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[1 2 3]
 [0 3 4]
 [0 0 0]
 [2 4 4]
 [2 1 2]
 [0 0 0]
 [3 3 1]
 [4 0 4]
 [0 2 4]
 [3 3 3]]
[[1 2 3]
 [0 3 4]
 [2 4 4]
 [2 1 2]
 [3 3 1]
 [4 0 4]
 [0 2 4]]


95. 将一个整数向量转换为matrix binary的表现形式 (★★★)

In [142]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. 给定一个二维数组，如何提取出唯一的(unique)行?(★★★)¶

In [143]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 0]]


97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数(★★★)

In [144]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
5.255334110802031


98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)? (★★★)
Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [145]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [146]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
(Compute bootstrapped 95% confidence intervals for the mean of a 1D array X，i.e. resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [147]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.24805     0.15256765]
